import { cn } from "@/lib/utils";
import type { AnalysisStatus, DataSource, HealthStatus } from "@/types";
import { FlaskConical } from "lucide-react";

const base = "inline-flex items-center gap-1.5 rounded-sm border px-1.5 py-0.5 text-xs font-medium whitespace-nowrap";

export function HealthBadge({ status }: { status: HealthStatus | null }) {
  const map: Record<HealthStatus, [string, string]> = {
    healthy: ["Healthy", "border-success/30 bg-success/10 text-success"],
    attention: ["Attention required", "border-warning/40 bg-warning/15 text-warning-foreground"],
    high_stress: ["High visual stress", "border-destructive/30 bg-destructive/10 text-destructive"],
    unknown: ["Not assessed", "border-border bg-muted text-muted-foreground"],
  };
  const [label, cls] = map[status ?? "unknown"];
  return (
    <span className={cn(base, cls)}>
      <span className="h-1.5 w-1.5 rounded-full bg-current" />
      {label}
    </span>
  );
}

export function StatusBadge({ status }: { status: AnalysisStatus }) {
  const map: Record<AnalysisStatus, [string, string]> = {
    queued: ["Queued", "bg-muted text-muted-foreground"],
    processing: ["Processing", "border-primary/30 bg-accent text-accent-foreground"],
    completed: ["Completed", "border-success/30 bg-success/10 text-success"],
    failed: ["Failed", "border-destructive/30 bg-destructive/10 text-destructive"],
    vision_unavailable: ["Vision unavailable", "border-warning/40 bg-warning/15 text-warning-foreground"],
  };
  const [label, cls] = map[status];
  return <span className={cn(base, cls)}>{label}</span>;
}

export function SourceBadge({ source, className }: { source: DataSource; className?: string }) {
  if (source !== "demo") return null;
  return (
    <span className={cn(base, "border-dashed border-warning/60 bg-warning/10 text-warning-foreground", className)} title="Generated by the demo adapter — not a real OpenCV result">
      <FlaskConical className="h-3 w-3" /> Demo
    </span>
  );
}

/** Renders a metric honestly: real value, a labelled demo value, or a waiting state. */
export function MetricValue({ value, unit, source, className }: { value: number | null | undefined; unit?: string | undefined; source: DataSource; className?: string }) {
  if (value == null)
    return <span className={cn("text-sm font-normal text-muted-foreground", className)}>{source === "demo" ? "Not provided" : "Waiting for backend"}</span>;
  return (
    <span className={cn("font-tabular", className)}>
      {value}
      {unit && <span className="ml-0.5 text-muted-foreground">{unit}</span>}
    </span>
  );
}
