import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { ArrowLeft, Bot, Check, CircleDashed, Eye, Loader2, RotateCcw, SkipForward, X, AlertTriangle, Lightbulb } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Panel, ErrorState } from "@/components/app/states";
import { HealthBadge, MetricValue, SourceBadge, StatusBadge } from "@/components/app/badges";
import { ImageViewer } from "@/components/cv/ImageViewer";
import { CvLegend, CvOverlay, type OverlayLayer, type OverlayRegion } from "@/components/cv/CvOverlay";
import { getAnalysis, pipelineOf, signedUrl, type AnalysisDetail } from "@/services/analysisService";
import { cn } from "@/lib/utils";
import type { PipelineStep } from "@/types";

export const Route = createFileRoute("/_authenticated/analyses/$id")({
  head: () => ({ meta: [{ title: "Crop Analysis Result — CropSense AI" }, { name: "description", content: "Computer-vision result, agent activity and recommendations." }] }),
  component: AnalysisPage,
});

function AnalysisPage() {
  const { id } = Route.useParams();
  const q = useQuery({
    queryKey: ["analysis", id],
    queryFn: () => getAnalysis(id),
    refetchInterval: (query) => (query.state.data?.status === "processing" || query.state.data?.status === "queued" ? 1200 : false),
  });
  const original = q.data?.analysis_images.find((i) => i.kind.startsWith("original"));
  const img = useQuery({ queryKey: ["signed", original?.storage_path], queryFn: () => signedUrl(original!.storage_path), enabled: !!original, staleTime: 30 * 60e3 });

  if (q.isLoading) return <div className="space-y-4"><Skeleton className="h-10 w-72" /><Skeleton className="h-96 w-full" /></div>;
  if (q.error) return <ErrorState message="Could not load this analysis." onRetry={() => q.refetch()} />;
  if (!q.data) return <ErrorState title="Analysis not found" message="It may have been deleted, or it belongs to another account." />;
  const a = q.data;
  const inProgress = a.status === "processing" || a.status === "queued";

  return (
    <>
      <Link to="/history" className="mb-4 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Analysis history</Link>
      <div className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
        <div>
          <p className="eyebrow">Analysis {a.id.slice(0, 8)}</p>
          <h1 className="mt-1 text-xl font-semibold tracking-tight">{inProgress ? "Analysis in Progress" : "Crop Analysis Result"}</h1>
          <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
            <span>{new Date(a.created_at).toLocaleString()}</span>
            <span>Field: {a.fields?.name ?? "—"}</span>
            <span>Crop: {a.crop_type}</span>
            <span className="capitalize">Mode: {a.mode}</span>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <StatusBadge status={a.status} />
          {a.status === "completed" && <HealthBadge status={a.health_status} />}
          <SourceBadge source={a.source} />
        </div>
      </div>

      {a.source === "demo" && (
        <p className="mb-4 rounded-md border border-dashed border-warning/60 bg-warning/10 px-3 py-2 text-xs text-warning-foreground">
          Demo mode: values on this page were generated by the mock vision adapter and rule-based agent. They are not real OpenCV results.
        </p>
      )}

      {a.status === "vision_unavailable" && (
        <div className="mb-4"><ErrorState title="Vision engine unavailable" message={a.error_message ?? "Your image was uploaded, but computer-vision processing is currently unavailable."} onRetry={() => q.refetch()} /></div>
      )}
      {a.status === "failed" && <div className="mb-4"><ErrorState title="Analysis failed" message={a.error_message ?? "The analysis could not be completed."} /></div>}

      {inProgress ? (
        <div className="grid gap-4 lg:grid-cols-[1fr_1.2fr]">
          <Panel title="Pipeline"><Pipeline steps={pipelineOf(a)} /></Panel>
          <ImageViewer src={img.data ?? null} alt="Uploaded crop image" isVideo={original?.kind === "original_video"} label={<Tag>Original</Tag>}>
            <div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="animate-scan h-px w-full bg-cv-scan" /></div>
          </ImageViewer>
        </div>
      ) : (
        <Result a={a} imgUrl={img.data ?? null} isVideo={original?.kind === "original_video"} />
      )}
    </>
  );
}

function Tag({ children }: { children: React.ReactNode }) {
  return <span className="rounded-sm bg-ink/80 px-1.5 py-0.5 font-mono text-[11px] text-ink-foreground">{children}</span>;
}

function Pipeline({ steps }: { steps: PipelineStep[] }) {
  const icon = (s: PipelineStep["state"]) =>
    s === "completed" ? <Check className="h-3.5 w-3.5" /> : s === "processing" ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : s === "failed" ? <X className="h-3.5 w-3.5" /> : s === "skipped" ? <SkipForward className="h-3.5 w-3.5" /> : <CircleDashed className="h-3.5 w-3.5" />;
  return (
    <ol className="space-y-0">
      {steps.map((s, i) => (
        <li key={s.key} className="relative flex gap-3 pb-4 last:pb-0">
          {i < steps.length - 1 && <span className={cn("absolute left-[11px] top-6 h-[calc(100%-16px)] w-px", s.state === "completed" ? "bg-primary" : "bg-border")} />}
          <span className={cn("z-10 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border",
            s.state === "completed" && "border-primary bg-primary text-primary-foreground",
            s.state === "processing" && "border-primary bg-accent text-primary",
            s.state === "failed" && "border-destructive bg-destructive text-destructive-foreground",
            (s.state === "pending" || s.state === "skipped") && "bg-card text-muted-foreground")}>{icon(s.state)}</span>
          <div className="min-w-0 flex-1">
            <div className="flex items-center justify-between gap-2">
              <span className={cn("text-sm", s.state === "pending" ? "text-muted-foreground" : "font-medium")}>{i + 1}. {s.label}</span>
              <span className="font-mono text-[11px] capitalize text-muted-foreground">{s.state}</span>
            </div>
            {s.detail && <p className="text-xs text-muted-foreground">{s.detail}</p>}
          </div>
        </li>
      ))}
    </ol>
  );
}

function Result({ a, imgUrl, isVideo }: { a: AnalysisDetail; imgUrl: string | null; isVideo: boolean }) {
  const [layer, setLayer] = useState<OverlayLayer>("processed");
  const regions: OverlayRegion[] = a.analysis_regions.map((r, i) => ({
    id: r.label.replace("Region ", "") || `R${i + 1}`, label: r.label, x: r.x, y: r.y, w: r.w, h: r.h,
    contour: r.contour as [number, number][] | null, area_percent: r.area_percent, severity: r.severity,
  }));
  const actions = [...a.agent_actions].sort((x, y) => x.seq - y.seq);
  const processedUrl = a.analysis_images.find((i) => i.kind === "processed_url")?.storage_path ?? null;

  const metrics = [
    { label: "Image Quality", v: a.image_quality_score, unit: "/100" },
    { label: "Vegetation Coverage", v: a.vegetation_coverage, unit: "%" },
    { label: "Suspicious Regions", v: a.suspicious_region_count, unit: "" },
    { label: "Affected Area", v: a.affected_area, unit: "%" },
    { label: "Analysis Confidence", v: a.confidence, unit: "%" },
  ];

  return (
    <>
      <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-5">
        {metrics.map((m) => (
          <div key={m.label} className="rounded-md border bg-card p-3">
            <div className="flex items-center justify-between text-xs text-muted-foreground">{m.label}{a.source === "demo" && m.v != null && <span className="font-mono text-[10px] text-warning-foreground">DEMO VALUE</span>}</div>
            <div className="mt-1 text-2xl font-semibold"><MetricValue value={m.v} unit={m.unit} source={a.source} /></div>
          </div>
        ))}
      </div>

      <Tabs defaultValue="overview" className="mt-6">
        <TabsList className="flex-wrap">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="vision">Vision Analysis</TabsTrigger>
          <TabsTrigger value="measurements">Measurements</TabsTrigger>
          <TabsTrigger value="agent">Agent Activity</TabsTrigger>
          <TabsTrigger value="recs">Recommendations</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="mt-4 space-y-4">
          <div className="grid gap-4 lg:grid-cols-2">
            <div><p className="eyebrow mb-2">Original image</p><ImageViewer src={imgUrl} alt="Original crop image" isVideo={isVideo} label={<Tag>Original</Tag>} /></div>
            <div>
              <p className="eyebrow mb-2">Computer vision result</p>
              <ImageViewer src={processedUrl ?? imgUrl} alt="Computer-vision annotated result" isVideo={isVideo && !processedUrl} label={<Tag>{processedUrl ? "Processed (engine)" : "Annotated overlay"}</Tag>}>
                {!processedUrl && <CvOverlay regions={regions} layer="processed" />}
              </ImageViewer>
            </div>
          </div>
          <CvLegend />
          <Panel title="Visual assessment">
            <p className="text-sm leading-relaxed">{a.final_assessment ?? "No assessment available."}</p>
            {a.agent_decision && <p className="mt-2 font-mono text-xs text-primary">Agent decision: {a.agent_decision}</p>}
            {a.notes && <p className="mt-3 text-xs text-muted-foreground">Notes: {a.notes}</p>}
          </Panel>
        </TabsContent>

        <TabsContent value="vision" className="mt-4 space-y-3">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex rounded-md border p-0.5 text-sm" role="tablist">
              {([["original", "Original"], ["mask", "Vegetation mask"], ["regions", "Suspicious regions"], ["processed", "Processed"]] as const).map(([k, l]) => (
                <button key={k} role="tab" aria-selected={layer === k} onClick={() => setLayer(k)} className={cn("rounded-sm px-3 py-1", layer === k ? "bg-accent font-medium" : "text-muted-foreground")}>{l}</button>
              ))}
            </div>
            <CvLegend />
          </div>
          <div className="mx-auto max-w-4xl">
            <ImageViewer src={layer === "processed" && processedUrl ? processedUrl : imgUrl} alt="Vision visualisation" isVideo={isVideo} label={<Tag>{layer}</Tag>}>
              {!(layer === "processed" && processedUrl) && <CvOverlay regions={regions} layer={layer} />}
            </ImageViewer>
          </div>
          {a.analysis_regions.length > 0 && (
            <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
              {a.analysis_regions.map((r) => (
                <div key={r.id} className="rounded-md border bg-card p-3 text-sm">
                  <div className="flex items-center justify-between"><span className="font-medium">{r.label}</span><span className={cn("font-mono text-xs", r.severity === "high" ? "text-destructive" : "text-warning-foreground")}>{r.severity}</span></div>
                  <div className="mt-1 font-mono text-xs text-muted-foreground">area {r.area_percent ?? "—"}% · {r.reanalyzed ? "re-analysed" : "initial pass"}</div>
                </div>
              ))}
            </div>
          )}
        </TabsContent>

        <TabsContent value="measurements" className="mt-4">
          <Panel title="OpenCV measurements">
            {a.analysis_measurements.length ? (
              <dl className="divide-y">
                {a.analysis_measurements.map((m) => (
                  <div key={m.id} className="flex items-center justify-between py-2.5 text-sm">
                    <dt>{m.label} <span className="ml-2 font-mono text-xs text-muted-foreground">{m.key}</span></dt>
                    <dd className="font-mono"><MetricValue value={m.value} unit={m.unit ?? ""} source={a.source} /></dd>
                  </div>
                ))}
              </dl>
            ) : <p className="text-sm text-muted-foreground">{a.source === "demo" ? "No measurements recorded." : "Waiting for backend."}</p>}
          </Panel>
        </TabsContent>

        <TabsContent value="agent" className="mt-4">
          <Panel title={<span className="flex items-center gap-2"><Bot className="h-4 w-4" /> Agent Activity</span>} actions={<span className="text-xs text-muted-foreground">{a.source === "demo" ? "Rule-based demo policy" : "Agent provider"}</span>}>
            {actions.length ? (
              <ol className="relative space-y-5 border-l pl-6">
                {actions.map((ev) => (
                  <li key={ev.id} className="relative">
                    <span className={cn("absolute -left-[33px] flex h-6 w-6 items-center justify-center rounded-full border bg-card", ev.actor === "agent" ? "text-primary" : "text-muted-foreground")}>
                      {ev.actor === "agent" ? <Bot className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
                    </span>
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="text-sm font-medium">{ev.action}</span>
                      <span className="rounded-sm bg-muted px-1.5 font-mono text-[10px] uppercase">{ev.actor === "agent" ? "Agent" : "OpenCV"}</span>
                      <span className="font-mono text-[11px] text-muted-foreground">{new Date(ev.created_at).toLocaleTimeString()} · {ev.status}</span>
                    </div>
                    <p className="mt-0.5 text-sm text-muted-foreground">{ev.description}</p>
                  </li>
                ))}
              </ol>
            ) : <p className="text-sm text-muted-foreground">No agent activity recorded.</p>}
          </Panel>
        </TabsContent>

        <TabsContent value="recs" className="mt-4">
          {a.recommendations.length ? (
            <div className="grid gap-3 md:grid-cols-2">
              {a.recommendations.map((r) => (
                <div key={r.id} className={cn("rounded-md border bg-card p-4", r.severity === "high" && "border-destructive/40", r.severity === "attention" && "border-warning/50")}>
                  <div className="flex items-center gap-2">
                    {r.severity === "info" ? <Lightbulb className="h-4 w-4 text-primary" /> : <AlertTriangle className={cn("h-4 w-4", r.severity === "high" ? "text-destructive" : "text-warning")} />}
                    <h3 className="text-sm font-semibold">{r.title}</h3>
                  </div>
                  <p className="mt-2 text-sm text-muted-foreground">{r.reason}</p>
                  {r.next_step && <p className="mt-2 text-sm"><span className="font-medium">Next step:</span> {r.next_step}</p>}
                </div>
              ))}
            </div>
          ) : <p className="text-sm text-muted-foreground">No recommendations.</p>}
          <p className="mt-4 text-xs text-muted-foreground">Recommendations are based on visual measurements only and are not treatment advice.</p>
        </TabsContent>
      </Tabs>
      <div className="mt-6"><Button asChild variant="outline"><Link to="/analyze"><RotateCcw className="h-4 w-4" /> New analysis</Link></Button></div>
    </>
  );
}
